apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pynw7zc12-nodejs 
  janus-idp.io/tekton: pynw7zc12-nodejs
  backstage.io/kubernetes-id: pynw7zc12-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pynw7zc12-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml