apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pynw7zc12-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pynw7zc12-nodejs 
  name: pynw7zc12-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pynw7zc12-nodejs 
